### ISSUE TITLE
Turbo segfaults on vGPUs that don't support Unified Memory (Managed Memory)

### ISSUE THREAD

**Issue by aklein3** [ptal/turbo#17]
There is a significant limitation when running Turbo on a virtualized GPU (vGPU): The GPU has no access to Unified Memory.  This is because the NVIDIA GRID hypervisor does not support Unified Memory in many situations.

> ### [2.10 Unified Memory Support](https://docs.nvidia.com/ai-enterprise/2.3/release-notes/index.html)
>
> Unified memory is a single memory address space that is accessible from
> any CPU or GPU in a system. It creates a pool of managed memory that is
> shared between the CPU and GPU to provide a simple way to allocate and
> access data that can be used by code running on any CPU or GPU in the system.
> Unified memory is supported only on a subset of vGPUs and guest OS releases...
>
> Only time-sliced vGPUs that are allocated all of the physical GPU's
> frame buffer on physical GPUs that support unified memory are supported.
>
> Linux only. Unified memory is **not** supported on Windows.
>
> When unified memory is enabled for a VM, vGPU migration is disabled
> for the VM.

This issue is related to #16.  

The problem is that battery's call to `cudaMallocManaged` does not check for `cudaErrorNotSupported` so it segfaults.

Major projects like PyTorch have a conditional runtime switch to run with or without UM.  

I have a pull-request that ports Turbo to Windows, but I can't test it on Azure's HCI because of the UM limitation.

I have since updated my proposed PR to add a new runtime option to turn off UM (-gpu-opt no-um). It checks at runtime if the GPU supports UM (`cudaDevAttrManagedMemory`, `cudaDevAttrConcurrentManagedAccess`) to set the option implicitly. I have not yet hooked it into `gpu_solving.hpp`.  There is a clean division between kernel and non-kernel code in the solver, so it looks doable. I think the trick might involve inventing a new kind of shared_ptr where the .get() moves the memory to/from the GPU (.getdev() and .gethost()).

I plan on tackling it in a few days.  It should fix #16 too.

I'm stuck right now because main is broken https://github.com/lattice-land/lala-core/issues/6

**Comment by ptal** [comment]
Thanks for raising this issue, I wasn't aware that in some (recent) settings UM is not available.

But without UM, it's going to be quite difficult, here some of the things to take into account:
* There is a producer/consumer between CPU and GPU using atomics so we print the solutions on the CPU. The reason is that, for some problems, printing directly from the GPU was too slow.
* The timeout is also handled on the CPU side and communicated through the `GridData::cpu_stop` Boolean variable.
* Even if you port the timeout to the GPU side (which seems to be possible), `cpu_stop` is also used for CTRL-C cancellation.

With cuda_battery, and in all lattice-land libraries, I have worked to make the code both executable from the CPU and GPU, and avoid methods like `getdev` or `gethost`. Normally you don't need that. I exclusively rely on the allocator type to know where to allocate. The issue you are going to face is to transfer all the data structures from the CPU to the GPU without UM. I guess we would need to modify the data structures in cuda-battery (`vector`, `shared_ptr`, ...) to support copying memory from a CPU `standard_allocator` to a GPU `global_allocator`, but that means using the CUDA API `cudaMemcpy` and the like, which are byte-copy and do not care about objects. Unless there is an easy mechanism (other than UM) to copy abritrary data structures (with array and pointers) that I'm not aware of?

I have no problem supporting Windows.
For non-UM support, it would make things less flexible, which might not be a good thing, especially since it's an early development stage. Not sure if the Azura HCI use-case is worth the pain (yet).
